### ISSUE TITLE
Use/Misuse Case 6 (Email Tracker)

### ISSUE THREAD

**Issue by DoomDragoon** [Deeds101/CYBR8420-project#16]

**Comment by DoomDragoon** [comment]
Kendra will work on Email Tracker feature

**Comment by kdherrm88** [comment]
uploaded use/misuse case diagram rough draft

**Comment by DoomDragoon** [comment]
One thing I would change with your rough draft is make the colors black. Im not sure how important that is, its just what all the lectures show. I will ask about it on our check in to be certain.

**Comment by Atmcalpine** [comment]
Was the diagram deleted?  I'm not able to view it for some reason.

**Comment by DoomDragoon** [comment]
Its in the folder on the main branch

**Comment by kdherrm88** [comment]
I did it in visio, I can change it after today

**Comment by kdherrm88** [comment]
![use misuse Case](https://github.com/Deeds101/CYBR8420-project/assets/142923995/2b3b92f4-c6ea-416f-9871-978035908cc7)

**Comment by kdherrm88** [comment]
![use misuse case](https://github.com/Deeds101/CYBR8420-project/assets/142923995/548b2242-f9a4-49fa-833a-2e598274782a)

**Comment by kdherrm88** [comment]
![use misuse case](https://github.com/Deeds101/CYBR8420-project/assets/142923995/b870b37c-a2a0-4fe0-a0d2-311418e26c8e)

**Comment by kdherrm88** [comment]
Added updated use/misuse case here. When created in draw.io it is a white background, don't know why it's showing as black here. Colors are inverted.

**Comment by Cojajomaco** [comment]
I would see about condensing your diagram to be direct correlations. The use cases, I believe, should be assumed to work and be “positives”. The misuses should directly counteract one of the use cases to iteratively improve upon security controls.

**Comment by kdherrm88** [comment]
![use misuse case (email tracking)](https://github.com/Deeds101/CYBR8420-project/assets/142923995/f4a85683-3516-4928-8856-73bbc48cb523)

**Comment by kdherrm88** [comment]
![use misuse case (email tracking)](https://github.com/Deeds101/CYBR8420-project/assets/142923995/aedddc11-ae9c-4bef-8d59-6d302a622a8f)

**Comment by kdherrm88** [comment]
![use misuse case (email tracking)](https://github.com/Deeds101/CYBR8420-project/assets/142923995/74d06366-4100-473d-bf01-3e692c7bdbdf)

**Comment by Deeds101** [comment]
What I would add is arrows to show the dependencies, It makes the diagram overall easier to read. This is looking really good so far.

**Comment by kdherrm88** [comment]
![use misuse case (email tracking)](https://github.com/Deeds101/CYBR8420-project/assets/142923995/0910eae7-d3d6-4c65-842d-7a76594c656b)

**Comment by kdherrm88** [comment]
added arrows

**Comment by Atmcalpine** [comment]
I'm not sure I understand how the threat of flooding the inbox with excessive tickets would threaten emails not being placed in the correct inbox folder.  I would think this would only exacerbate the issue.  Might need to tweak this section.

**Comment by kdherrm88** [comment]
In reviewing the forum for ITFlow, there was a ticket created for them to address an issue where an email was sent into the IT Helpdesk for a company and it continually created new tickets within the ITFlow dashboard. This could potentially cause problems if the emails were automatically routed to the folder to create a ticket, and since the parser runs with a cronjob, it could easily overload the dashboard, and eventually the IT Helpdesk workers. According to the forum, this issue was fixed with a code push 5 days ago.
