### ISSUE TITLE
Hello :) - Question Re SQL Injection

### ISSUE THREAD

**Issue by wrongecho** [Deeds101/CYBR8420-project#21]
Hello team,

Johnny and I have been following your repository for a while. We're honoured that you've chosen ITFlow for your research project.

ITFlow is still in Beta, but seems to be gaining a large following recently. Fixing security issues is a priority for us. But it's worth mentioning that Johnny and I are sysadmins, not developers. 

When reading your "Use-Misuse_Case_Submission_Doc.md" document, I noticed you've mentioned that you found a SQL Injection vulnerability?

If this (or any other) vulnerability is still present in the code, I would kindly request you to responsibly disclose it via Github Security Advisories: https://github.com/itflow-org/itflow/security/policy

If you've any other feedback, please do feel free to get in touch on the forum.

I look forward to hearing from you :)

**Comment by DoomDragoon** [comment]
Hello sir! 

I am the lead for our little research group. I wasn't aware you knew of our research into ITFlow yet, so this is a pleasant surprise! 

In terms of the SQL injection, we did not find a vulnerability. In that specific case we were referencing a closed issue and its resolution.

I assure you, if we come across any security threats, we will follow the procedure detailed in your stated security policy. We will not post them publicly like a loon.

Thank you!

**Comment by wrongecho** [comment]
Hey DoomDragoon, it's great to meet you!

I think one of your team starred the repo* and piqued our interest :) 

Thank you for confirming regarding the security issues. I just wanted to make sure, to ensure the safety and security of our users.

We do hope one day to fund a full security assessment of ITFlow, but these are expensive! Again, if you have any questions or concerns please don't hesitate to reach out. 

Thanks & Take care!
