### ISSUE TITLE
Claim Assurance Case #2 Database Stuff

### ISSUE THREAD

**Issue by DoomDragoon** [Deeds101/CYBR8420-project#23]

**Comment by DoomDragoon** [comment]
First draft, just wanted to get it out there so people can see some progress.
![Assurance Claim Diagram](https://github.com/Deeds101/CYBR8420-project/assets/107895832/8d940df5-c7c6-4ef4-be79-176bb765a4f7)

**Comment by Atmcalpine** [comment]
So far so good.  I'm glad you called out input validation because I was having a blank moment earlier when I tried to reference that control for my diagram as well.  The only item I would add is attend a context number (CT#) to the item on your diagram.

**Comment by Cojajomaco** [comment]
@DoomDragoon I would suggest revising your Top Level Claim. "The database is secure", to me, assumes full, impenetrable security which is not possible in a risk/cost analysis. I would revise the wording to be similar to "The database has sufficient protections", "is sufficiently secure", or something of that sort.

**Comment by DoomDragoon** [comment]
Little bit of progress but still working things out
![Draft1Assurance Claim Diagram](https://github.com/Deeds101/CYBR8420-project/assets/107895832/75d00cae-5a96-4681-99ec-b6ee16e9526a)

**Comment by kdherrm88** [comment]
I like where you're going with this. Will you put a rebuttal under sub-claim2 or evidence? Seems like you could really go either way if you have a rebuttal to add there.

**Comment by DoomDragoon** [comment]
Working on encryption next
![Draft1Assurance Claim Diagram](https://github.com/Deeds101/CYBR8420-project/assets/107895832/2b060227-ee68-4489-bffd-4faf415dacd0)

**Comment by DoomDragoon** [comment]
I think this is pretty close to my final.
![Draft1Assurance Claim Diagram](https://github.com/Deeds101/CYBR8420-project/assets/107895832/cea16e29-9626-4669-b472-a87286c47c0e)

**Comment by DoomDragoon** [comment]
Fixed notation errors
![Draft1Assurance Claim Diagram](https://github.com/Deeds101/CYBR8420-project/assets/107895832/04f08e48-d694-49db-9f39-4bf08a266b8b)

**Comment by DoomDragoon** [comment]
I think this is my final
![Draft1Assurance Claim Diagram](https://github.com/Deeds101/CYBR8420-project/assets/107895832/1ccc7ae8-173f-4086-acc9-430c5d3a69fd)
