### ISSUE TITLE
Claim Assurance Case #3 - MFA

### ISSUE THREAD

**Issue by DoomDragoon** [Deeds101/CYBR8420-project#24]

**Comment by bdog711998** [comment]
ITflow's MFA security verification minimizes the possibility of infiltration by malicious attackers

**Comment by bdog711998** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/104231228/f0fc6d88-4984-4b8a-9e4d-9761fed5a6a5)

**Comment by Atmcalpine** [comment]
For the top level claim, I might adjust it to say" ITFlow's MFA control sufficiently minimizes the risk of infiltration."

**Comment by bdog711998** [comment]
Thinking a bit 'Wordy' on the initial claim?

**Comment by DoomDragoon** [comment]
I think less is more for these diagrams. Its an entity, followed by a value for the property, followed by the critical property. So maybe "IT Flow effectively utilizes MFA security requirements" Then your chart would go into detail about how it prevents infiltration etc.
![image](https://github.com/Deeds101/CYBR8420-project/assets/107895832/e18e4943-6b4c-44a3-bf38-0934b25f25c8)

**Comment by kdherrm88** [comment]
Brevin, do you have evidence for these claims?

**Comment by bdog711998** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/104231228/8cc965ab-3724-422b-a2f5-310336eae808)

**Comment by bdog711998** [comment]
Made recommended changes as well as added evidence to original

**Comment by bdog711998** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/104231228/59909fa9-2c53-457b-827d-55c6bbb5b7b1)
