### ISSUE TITLE
Claim Assurance Case #5 - RBAC

### ISSUE THREAD

**Issue by DoomDragoon** [Deeds101/CYBR8420-project#26]

**Comment by Deeds101** [comment]
Potential claim for Role Based Access control: Role Based Access control provides sufficient access to user accounts

**Comment by Deeds101** [comment]
Talking to the professor i have adjusted my claim: ITFlow provides secure access to roles in the environment.

**Comment by Deeds101** [comment]
Draft 1 RBAC within ITFlow:


![Image](https://github.com/Deeds101/CYBR8420-project/assets/142707419/5d058f1c-ddeb-4049-aaa4-2aa40e4e66c2)

**Comment by kdherrm88** [comment]
Good call on referencing other claims, and I like the sub-claims. Do you think there could be an undermining claim added anywhere?

**Comment by Deeds101** [comment]
That's what i was thinking about adding next, i just needed some time to think of more security related issues with the role based access controls.

**Comment by Deeds101** [comment]
RBAC Assurance claim draft 2:

Added more information as well as took teammates comments into consideration.



![Image](https://github.com/Deeds101/CYBR8420-project/assets/142707419/7a994e28-559d-4ef6-9e1f-2a059b5f8342)

**Comment by DoomDragoon** [comment]
This might just be my OCD but making the evidence bubbles larger might help with readability. Dont forget to ad E1, E2 etc to your evidence.

**Comment by Atmcalpine** [comment]
I believe the undermine items need to begin with an "unless..." statement.

**Comment by Deeds101** [comment]
RBAC Assurance Case Final Draft:



![Image](https://github.com/Deeds101/CYBR8420-project/assets/142707419/27f402d1-e416-4973-858c-af58dc4ee391)
