### ISSUE TITLE
Claim Assurance Case #6 - Workflow Automation and Documentation

### ISSUE THREAD

**Issue by DoomDragoon** [Deeds101/CYBR8420-project#27]

**Comment by kdherrm88** [comment]
Potential Claim:
ITFlow provides appropriate tracking of documentation and workflows.

**Comment by kdherrm88** [comment]
![assurance case](https://github.com/Deeds101/CYBR8420-project/assets/142923995/fde2a1b8-a986-4b09-94ea-744978133b7d)

**Comment by kdherrm88** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/142923995/991e7a34-bfeb-4d58-9743-1a4322e6cbb0)

**Comment by kdherrm88** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/142923995/1aff1e64-cd43-4d30-93cb-dd6c6ed35f6c)



forgot the circle at the bottom of the last one

**Comment by DoomDragoon** [comment]
I believe your box under E1 should be an Undermine, not a rebuttal. I would also reference Adams diagram in E2, he went very in depth with passwords.

**Comment by kdherrm88** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/142923995/0dccc097-2ba1-4d82-9563-79b246323e0e)


updated with suggestions

**Comment by kdherrm88** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/142923995/934b957a-b205-45dc-b902-a6f8a3ae69f2)

**Comment by Atmcalpine** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/87542247/c6579b5f-24ed-4e8e-bdf7-85ae04b55b42)
