### ISSUE TITLE
Database Stuff

### ISSUE THREAD

**Issue by Deeds101** [Deeds101/CYBR8420-project#30]

**Comment by DoomDragoon** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/107895832/270c52f9-270c-47c0-ab65-cd660f7b8b60)

**Comment by DoomDragoon** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/107895832/6be15299-2aa8-4397-bc61-f2ec328fb7d5)
Remade in TMT

**Comment by Cojajomaco** [comment]
Revision looks good - can you add Dr. Evil back in? :)

**Comment by DoomDragoon** [comment]
Combined with larger diagram
