### ISSUE TITLE
DFD Diagram 3

### ISSUE THREAD

**Issue by Deeds101** [Deeds101/CYBR8420-project#31]

**Comment by Cojajomaco** [comment]
This is my revised DFD attempt. I wanted to map the flow of data between the API to the app and the browser to the app. 
![image](https://github.com/Deeds101/CYBR8420-project/assets/143226996/e7cfaa36-2b22-491a-9a61-140f8039f1cd)

**Comment by Cojajomaco** [comment]
Greatly reduced the complexity and merged into the final DFD to be submitted shortly.
