### ISSUE TITLE
DFD - Workflow Automation and Documentation

### ISSUE THREAD

**Issue by Deeds101** [Deeds101/CYBR8420-project#32]

**Comment by kdherrm88** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/142923995/69471b3c-189c-411e-aba3-a82dc90f46bd)

**Comment by kdherrm88** [comment]
This may not be the flow I want, so feel free to rip it apart. I just wanted to have something started so I can continue from here.

**Comment by kdherrm88** [comment]
![image](https://github.com/Deeds101/CYBR8420-project/assets/142923995/1171d3c0-9dcb-4b7a-9d0a-eca3f1f256c1)

**Comment by kdherrm88** [comment]
Merged with final document
