### ISSUE TITLE
DFD Diagram 5 - Deeds101

### ISSUE THREAD

**Issue by Deeds101** [Deeds101/CYBR8420-project#33]

**Comment by Deeds101** [comment]
First rough draft 


![Image](https://github.com/Deeds101/CYBR8420-project/assets/142707419/8b47bb91-ea01-40eb-a517-b1e1ed60eebb)

**Comment by Atmcalpine** [comment]
We'll want to ensure we're in alignment on the authentication piece as our diagrams are very similar.  When we meet with the professor we should see if we should be combining all of our diagrams into a single diagram as I'm sure access management including RBAC will need to be incorporated into each diagram.

**Comment by Deeds101** [comment]
Second rough draft

![Image](https://github.com/Deeds101/CYBR8420-project/assets/142707419/275cf2b5-05b6-45ec-856e-4b54e3e461b4)
